# This is a config for E2B sandbox template.
# You can use template ID (o11loq27f4r0numsdj8r) or template name (vibe-nextjs-1759023284) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("vibe-nextjs-1759023284") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-1759023284") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-1759023284')

team_id = "22502b74-a28a-4dfc-bbf4-351e56cfc345"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-1759023284"
template_id = "o11loq27f4r0numsdj8r"
